"""restaurant enrichment fields

Revision ID: 0707ec78a5a7
Revises: d9589e4d32ff
Create Date: 2026-07-31 07:49:42.799378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0707ec78a5a7'
down_revision: Union[str, Sequence[str], None] = 'd9589e4d32ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('google_place_id', sa.String(length=255), nullable=True))
    op.add_column('restaurants', sa.Column('thumbnail', sa.String(length=500), nullable=True))
    op.add_column('restaurants', sa.Column('opening_hours', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'opening_hours')
    op.drop_column('restaurants', 'thumbnail')
    op.drop_column('restaurants', 'google_place_id')
    op.drop_column('restaurants', 'category')
    op.drop_column('restaurants', 'review_count')
    op.drop_column('restaurants', 'rating')
    # ### end Alembic commands ###
